service: yt-search-demo

provider:
  name: aws
  region: us-east-1

functions:
  yt-search-demo:
    name: yt-search-demo
    image: 294263178210.dkr.ecr.us-east-1.amazonaws.com/yt-search-demo:latest
    architecture: arm64
    timeout: 30
    vpc:
      securityGroupIds:
        - Ref: MountTargetSecurityGroup # Reference to the security group created in the resources section
      subnetIds:
        - subnet-0c2beb95982fb9412 # vpc-eussam-private-1
    fileSystemConfig:
      localMountPath: /mnt/efs
      arn:
        Fn::Join:
          - ''
          - - 'arn:aws:elasticfilesystem:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':access-point/'
            - Ref: EFSAccessPoint
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
    dependsOn:
      - MountTarget

resources:
  Resources:
    # Security Group for EFS Mount Target
    MountTargetSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: "yt-demo-efs-mount-target-sg"
        GroupDescription: "Mount target security group"
        Tags:
          - Key: Name
            Value: "yt-demo-efs-mount-target-sg"
        VpcId: vpc-0eb65e132a9daf249
        SecurityGroupIngress:
          # - IpProtocol: "-1"
          #   CidrIp: 0.0.0.0/0 # Adjust for tighter security
          - IpProtocol: tcp
            FromPort: 2049
            ToPort: 2049
            CidrIp: 0.0.0.0/0 # Adjust for tighter security

    # EFS File System
    EFSFileSystem:
      Type: AWS::EFS::FileSystem
      Properties:
        FileSystemTags:
          - Key: Name
            Value: yt-search-demo

    # EFS Access Point for Lambda Access
    EFSAccessPoint:
      Type: AWS::EFS::AccessPoint
      Properties:
        FileSystemId:
          Ref: EFSFileSystem
        PosixUser:
          Uid: "1001"
          Gid: "1001"
        RootDirectory:
          CreationInfo:
            OwnerGid: "1001"
            OwnerUid: "1001"
            Permissions: "755"
          Path: "/efs-hf-storage"

    # EFS Mount Targets
    MountTarget:
      Type: AWS::EFS::MountTarget
      Properties:
        FileSystemId:
          Ref: EFSFileSystem
        SubnetId: subnet-0c2beb95982fb9412 # Lambda subnet
        SecurityGroups:
          - Ref: MountTargetSecurityGroup

  # Outputs block must be placed under the resources block to be available in the cloudformation stack
  # Outputs:
  #   FileSystemId:
  #     Value:
  #       Ref: EFSFileSystem
  #   AccessPointId:
  #     Value:
  #       Ref: EFSAccessPoint
  #   MountTargetId:
  #     Value:
  #       Ref: MountTarget