# start from python base image
# FROM python:3.10
FROM public.ecr.aws/lambda/python:3.10

# change working directory
# WORKDIR /code
WORKDIR /var/task

# install build dependencies
RUN yum -y groupinstall "Development Tools"

# Install additional system dependencies
# RUN yum -y update && yum install -y procps

# add requirements file to image
COPY ./requirements.txt .

# install python libraries
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# add python code
COPY ./app ./app
# COPY ./app/ /code/app/

# set environment variable for Hugging Face cache directory pointing to AWS EFS volume mounted at /mnt/efs
ENV HF_HOME=/mnt/efs

# set environment variables to avoid CPU info parsing issues
ENV MKL_THREADING_LAYER=GNU
ENV OMP_NUM_THREADS=1
ENV MKL_NUM_THREADS=1

CMD ["app.main.handler"]
